### ISSUE TITLE
cipher is not called

### ISSUE THREAD

**Issue by fmccown** [dan7800/VulnerableAndroidAppOracle#1]
Examining your solution in com.example.hussienalrubaye.sender.MainActivity to encrypt the data, looks like you declare a method called cipher but never call it.  So the string is still being sent in the clear to the receiver activity.

The Descriptions.docx does not show this solution's code, only a screenshot of the encrypted text.

Is there a better encryption library that the user should be using?  The supplied solution could be easily decrypted.

**Comment by resurrexit** [comment]
Which activity does this particular Descriptions.docx belong to? I'll take a look at it.

**Comment by fmccown** [comment]
The file in question is VulnerableAndroidAppOracle/Vulnerabilities/Intent/Sender/app/src/main/java/com/example/hussienalrubaye/sender/MainActivity.java.  

I've communicated directly with @hussien89aa, and there are a number of issues with the code examples in this repo that are going to be addressed.  It's probably not a big deal that cipher is not called as the whole example needs to be revamped.

**Comment by resurrexit** [comment]
Perfect! I'm actually reworking that tutorial right now. The cipher's going to be replaced with something else, like a call to a crypto library.
