### ISSUE TITLE
Explain how "private variable cannot be reversed"

### ISSUE THREAD

**Issue by fmccown** [dan7800/VulnerableAndroidAppOracle#2]
In [VulnerableAndroidAppOracle/Vulnerabilities/XML/Descriptions.docx](https://github.com/dan7800/VulnerableAndroidAppOracle/blob/master/Vulnerabilities/XML/Descriptions.docx), the problem fix states that the Google API key should be saved in a private variable instead of an XML file because "the private variable cannot be reversed".  Could you please add more information to the docx why decompiling the dex into source code as [described here](http://stackoverflow.com/questions/1249973/decompiling-dex-into-java-sourcecode) would not reveal the API key?  [This posting](http://stackoverflow.com/questions/13854425/how-to-avoid-reverse-engineering-of-an-apk-file) suggests that even using code obfuscation tools is not going to help hide your API key.

**Comment by hussien89aa** [comment]
Hello,
You cannot use Google API key if it in Private variables. 
In while you could secure your Google API key from Google play API by restructuring using this key by specific computer and specific Android APP ID, so hacker cannot use it to change you more money from using Google services
